import Head from "next/head";
import { Box, Container, useColorModeValue } from "@chakra-ui/react";
import { Header } from "./Header";

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Finance Rapyd X App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        minH={"100vh"}
        align={"center"}
        justify={"center"}
        bg={useColorModeValue("gray.50", "gray.800")}
      >
        <Header />
        <Container maxW={"3xl"}>{children}</Container>
      </Box>
    </>
  );
}
