import Head from "next/head";
import { Spinner } from "@chakra-ui/react";


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Spinner color="red.500" />
      </main>
    </>
  );
}
